config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'form/new',to: 'form#new',as:  :new_form
  get 'form/', to: 'form#index', as: :forms
  get 'form/:id/edit', to: 'form#edit', as: :edit_form
  post 'form', to: 'form#create', as: :create_form
  get 'form/:id', to: 'form#show', as: :form
  put 'form/:id', to: 'form#update', as: :form_update
  delete 'form/:id', to: 'form#destroy', as: :form_delete
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    validates :name, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/form_controller.rb
class FormController < ApplicationController
  before_action :form_find, only: [:show,:destroy,:edit,:update]
  def index
    @forms = Form.all
  end
  
  def show
  end

  def edit
  end
  
  def update
    @form.update(email: params[:form][:email], name: params[:form][:name], phone: params[:form][:phone], issue: params[:form][:issue], message: params[:form][:message])
    if @form.present?
      redirect_to form_path(id: @form.id)
    end
  
  end
  
  def new
    @form = Form.new
  end
  def create
    @form = Form.create(email: params[:form][:email], name: params[:form][:name], phone: params[:form][:phone], issue: params[:form][:issue], message: params[:form][:message])
    if @form.present?
      redirect_to form_path(id: @form.id)
    end
  end
  
  def destroy
    @form.destroy
    redirect_to forms_path
  end

  private

    def form_find
      @form = Form.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def post_now post
        post.name + " now "
    end
end

app/views/form/_form.html.erb
<%= form_with model: form, method: method do |f|%>
    <%= f.email_field :email%>
    <%= f.text_field :name%>
    <%= f.text_field :phone%>
    <%= f.text_field :issue%>
    <%= f.text_area :message%>
    <%= f.submit "Enviar"%>
<% end %>

app/views/form/edit.html.erb
<%= render 'form', form: @form, method: "put"%>

app/views/form/index.html.erb
<% @forms.each do |form|%>
    <p>id: <%= form.id%>,nome: <%= form.name%>,email: <%= form.email%>, assunto: <%= form.issue%>,mensagem<%= form.message%></p>
    <%= link_to  "clique", form_path(id: form.id) %>|<%= link_to  "Apagar", form_delete_path(id: form.id), method: :delete %>|<%= link_to  "Editar", edit_form_path(id: form.id) %>
<% end %>

app/views/form/new.html.erb
<h1>Form#new</h1>
<%= render 'form', form: @form, method: 'post'%>

app/views/form/show.html.erb
<h1>Aqui é o show</h1>

<p>id: <%= @form.id%>,nome: <%= @form.name%>, email: <%= @form.email%>, assunto: <%= @form.issue%>, mensagem<%= @form.message%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aula2Tarde</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post_now post %></td>
        <%if post.message.present?%>
          <td><%= post.message %></td>
        <% end %>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @post.message %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>